### ISSUE TITLE
Font Size property not working

### ISSUE THREAD

**Issue by angeldukes** [cdaein/mica-gd220#10]
The Font Size property is working fine for the titles and headings but, when I try to change it for the body text the size seems to not be changing unless I use a high number. The first picture shows font size at 6pt and the second one shows font size at 7pt. The last image shows what it's supposed to look like and the font size in the mockup is 16pt.

<img width="911" alt="Screen Shot 2020-04-04 at 11 38 46 PM" src="https://user-images.githubusercontent.com/60227885/78466438-191f2200-76cf-11ea-8503-21ad1dc48a3c.png">
<img width="904" alt="Screen Shot 2020-04-04 at 11 39 01 PM" src="https://user-images.githubusercontent.com/60227885/78466439-1a504f00-76cf-11ea-9a63-02d5ff0bae58.png">
<img width="746" alt="Screen Shot 2020-04-04 at 11 36 01 PM" src="https://user-images.githubusercontent.com/60227885/78466450-3a800e00-76cf-11ea-83f3-c486b160baae.png">
<img width="449" alt="Screen Shot 2020-04-04 at 11 36 35 PM" src="https://user-images.githubusercontent.com/60227885/78466451-3ce26800-76cf-11ea-8baa-eec61501750a.png">
<img width="852" alt="Screen Shot 2020-04-04 at 11 54 45 PM" src="https://user-images.githubusercontent.com/60227885/78466501-b2e6cf00-76cf-11ea-8979-23a22afb36f9.png">

**Comment by cdaein** [comment]
First, check your browser zoom level - reset to 100%. There is also a limit to a browser how small text can get.

I would also use `px` instead of `pt`. `pt` is for print, not for the web.
https://css-tricks.com/css-font-size/

12pt is equal to 16px. so if you set some text 6pt, that is 8px, which is very small.
