### ISSUE TITLE
Issues with div. box alignment

### ISSUE THREAD

**Issue by sgahler** [cdaein/mica-gd220#2]
I'm trying to put two col-50 half boxes together in a specific way, but I can't seem to get the bottom box to move up and fill the white space in the row before it.

![image](https://user-images.githubusercontent.com/46965100/53069727-ff128800-34aa-11e9-96c9-487913f96fc2.png) 

background 5 is the blue starred box and background 6 is the red starred box that I want beside it.
Here is the code written out:
<div class="col-50 quarter background2"></div>
            <div class="col-100 quarter background3"></div>
            <div class="col-50 quarter background4"></div>
            <div class="col-50 half background5"></div>
            <div class="col-50 half background6"></div>

Thanks in advance!

**Comment by cdaein** [comment]
First of all, for any columns to work, you need to place them inside `<div class="row">`:
```html
<div class="row">
  <div class="col-50 half background5"></div>
  <div class="col-50 half background6"></div>
</div>
```

Secondly, if these two columns are not aligned on top as your image describes, then, I don't think it will work. you will need to go back to Photoshop and re-slice them so all the columns in the same row will be aligned at the top of the row.

And here is another suggestion - looks like these backgrounds are just color gradient. In that case, you may not even need to slice images out, you can use CSS gradient as `background-color` instead.
