### ISSUE TITLE
 images not appearing + understanding error prompts

### ISSUE THREAD

**Issue by hdowuona** [cdaein/mica-gd220#3]
Hello everyone,

I'm having issues with my images not appearing as I write my HTML. In the class example, I was able to do it, so I'm not sure where I went wrong. Also, I have two error prompts from the brackets extension, but have can't figure out what they mean. For example, one message is "special characters must be escaped" I've been trying different things to fix it, so I probably made more errors in the process.

Here's a pic:

![screen shot 2019-02-20 at 9 41 46 pm](https://user-images.githubusercontent.com/47001821/53139794-cc26cd80-3558-11e9-875f-a715128f6a7b.png)

Best,

Hadassah

**Comment by cdaein** [comment]
can't say for sure but i notice a few things.

1. first thing first, let's use "beautify" to fix any formatting/indentation issues.
1. all your contents must be within `<div class="container">` but right now, everything is placed outside.
1. when you use *class* in html, you don't use *dot* in front of the name. check the line 46.
1. <div> on line 52 is missing closing tag.

i will first start with these and see how it goes. if you still have issues, check again small details like spelling errors, closing tags, quotation marks, angle brackets, etc.

**Comment by hdowuona** [comment]
Hello Dae In,

Thanks for replying. I've done what you said and the error messages are
gone, but I still have issues. I will follow your advice and check for
spelling errors again.

Best,

Hadassah

**Comment by slee30** [comment]
Maybe you fixed it already, but for the photo, I see error in line 30 and 48. You named your class as "img-song-title", but in like 30, you used **.song-title** instead of **.img-song-title**, so maybe try fixing name for line 30.
