### ISSUE TITLE
Swapped Left and Right Positioning

### ISSUE THREAD

**Issue by hdowuona** [cdaein/mica-gd220#4]
Hello Everyone,

I was trying to move some of my lyrics to the right of my screen(not text-align). However, when I enter in right, and then a value, it doesn't work. It will only move right when I enter left, then a value into CSS. This doesn't prevent me from laying out my lyrics, so I could just continue with my left and right swapped, but then it would be harder to fix later on. Any suggestions? 

Here's a pic:
![swapped left and right 1](https://user-images.githubusercontent.com/47001821/53287935-7288f380-3750-11e9-8854-38cbaee7a923.png)

**Comment by cdaein** [comment]
`left` property means that you start from the left edge and push towards right. so in this case, `left: 50%` looks good to me (just like the white text you have on top). If you continue setting text this way, you will probably alternate between `left` and `right` for each paragraph.

if you're not sure, you can also show another screenshot when you used `right:` and tell us what's wrong with it.

**Comment by hdowuona** [comment]
When I use right, the issue is that it pushes the text to the left edge. 
(as seen below)

![swapped left and right 2](https://user-images.githubusercontent.com/47001821/53291168-f22cb780-377c-11e9-86c9-1baddfb14780.png)

**Comment by cdaein** [comment]
That is the expected behavior. When you use `right` instead of `left`, then you are essentially setting *the anchor point* on the right side of your text block. Then, when you give `50%` as value, from the right edge, we push 50%. 

Similarly, when you use `left`, we set the anchor point on the left side of the block, and from there, we push in the other direction (towards right).

**Comment by hdowuona** [comment]
Ok I think I'm starting to understand. So is that element naturally part of
the program, or did I cause this?

I wonder if this is related to template default and program default
clashing, you were mentioning last class?

**Comment by cdaein** [comment]
Not sure I understood your question above, but I don't see anything wrong from your screenshots. Only thing that the template is doing here is that there is `position: absolute` somewhere, which makes possible to use `left` and `right` in your own style.

**Comment by hdowuona** [comment]
Ok thanks for clarifying!
