### ISSUE TITLE
The text code is moving background images

### ISSUE THREAD

**Issue by slee39** [cdaein/mica-gd220#5]
Hello this is Su Young Lee
I try to add a text after I added a background images, but the texts are moving my images then distorting their placement. 
But I cannot sure the reason why.
I attached the screenshot below and I feel happy to hear any ideas and concerns.
Sincerely, 
<img width="580" alt="screen shot 2019-03-05 at 4 36 12 am" src="https://user-images.githubusercontent.com/46966731/53795847-d6ee4480-3f00-11e9-9265-de37c8dbda35.png">
<img width="341" alt="screen shot 2019-03-05 at 4 35 09 am" src="https://user-images.githubusercontent.com/46966731/53795848-d6ee4480-3f00-11e9-989e-ea7639e64eb3.png">
<img width="540" alt="screen shot 2019-03-05 at 4 36 20 am" src="https://user-images.githubusercontent.com/46966731/53795849-d6ee4480-3f00-11e9-9154-b62efb0193c4.png">
<img width="652" alt="screen shot 2019-03-05 at 4 35 39 am" src="https://user-images.githubusercontent.com/46966731/53795850-d6ee4480-3f00-11e9-84e8-398e9a528d61.png">

**Comment by slee39** [comment]
+ I cannot move texts since then. the codes like 'top:80%' are not working to my texts. I assume I am missing one simple thing, but I cannot define what it is.

**Comment by cdaein** [comment]
hard to tell by looking at the screenshot.
below is what I would do. follow each step in order. and for each step, re-look at your code and re-run preview:

1. fix line breaks in your css.
1. run Beautify
1. save your file and check HTMLlint for any error message.
1. go over EVERY SINGLE LINE of your code and check for any missing brackets, semi-colons, etc. You really need to take time for this.
1. click on EVERY SINGLE HTML ELEMENT opening tag and make sure you have a corresponding ending tag.
1. isolate the problem. try commenting out a section one at a time and see whether it brings everything back. if so, then the section is likely casing the issue. if not, move on and continue to check other sections. (both HTML and CSS)
1. remove all classes from the element and re-write the classes. add them back in one at a time.
1. start over entire project from scratch and just add the small bit of code (the problematic row and columns) - does it look ok in this new version?

try these first and let us know.

**Comment by slee39** [comment]
Hello when I was I was checking errors
There's two repetitive errors that says 

'class value must match the format:underscore'
and
'indenting spaces must be used in groups of four'

What does this mean? How can I fix these? 

Sincerely,

<img width="575" alt="screen shot 2019-03-05 at 4 21 56 pm" src="https://user-images.githubusercontent.com/46966731/53838430-12215f80-3f63-11e9-965b-e3afef236f5c.png">

**Comment by slee39** [comment]
Sorry there's one more screenshot. 

<img width="594" alt="screen shot 2019-03-05 at 4 24 36 pm" src="https://user-images.githubusercontent.com/46966731/53838566-69bfcb00-3f63-11e9-92f9-b2a4a413d2b7.png">

**Comment by cdaein** [comment]
hmm, other than the error messages, are you still getting the same issue on the webpage? Not sure what the problem is... have you tried all my suggestions?

**Comment by slee39** [comment]
Hello Su Young Lee again. 
Oh, fortunately, the problem is solved since I tried the last suggestion (start over the entire project) although I cannot sure why. 
I sent these error messages when I was trying the third suggestion(check HTML lint for any error messages) because I cannot sure what do these are referring.

**Comment by cdaein** [comment]
sounds good. if you don't want to run into the same issue again, I will keep searching for the cause. Have working version and not-working version opened side by side, and compare line by line to see if there's any difference. (it may be a simple typo) it will be a tedious task but that's how we learn.
