### ISSUE TITLE
Template Measurements Don't Match with Brackets

### ISSUE THREAD

**Issue by hdowuona** [cdaein/mica-gd220#6]
Hello everyone,

I tried to measure the distance in pixels between elements in my template with the ruler tool. However when I entered the same number to position in brackets, it doesn't match and I have to go with a number significantly lower for it to work. See pic attached. Please advise.

![distance issue](https://user-images.githubusercontent.com/47001821/55347448-ee2e3c80-5482-11e9-89c2-2fb563f33a73.png)

Thanks,

Hadassah

**Comment by cdaein** [comment]
The first thing I will check is what the parent element of `.circle-1` is. With `absolute` positioning, the circle will look at its positioned parent (or ancestor) to position itself. Or it could be the animation you applied to the circle that is also controlling `top` property?

**Comment by hdowuona** [comment]
Yes I've looked into what you've said, and saw that my animation is
affecting my top property. I've managed to fix it.

Thanks!

Best,

Hadassah
