### ISSUE TITLE
Trouble with textpath and svg not working.

### ISSUE THREAD

**Issue by mattalancarter** [cdaein/mica-gd220#7]
I'm attempting to have text follow a defined SVG path using a transparent curve and \<textpath>. The text shows up and is properly formatted but does not follow the path, nor does the path draw correctly (as evidenced by the addition of the test class). I've included screenshots of my html, css, and of the preview.
 
<img width="565" alt="Screen Shot 2020-03-02 at 9 25 54 AM" src="https://user-images.githubusercontent.com/60264026/75684972-d39ead80-5c67-11ea-9af3-2f0e8ced1bfa.png">
<img width="360" alt="Screen Shot 2020-03-02 at 9 26 35 AM" src="https://user-images.githubusercontent.com/60264026/75685031-ea450480-5c67-11ea-9b5e-6c52a7916865.png">
<img width="981" alt="Screen Shot 2020-03-02 at 9 26 48 AM" src="https://user-images.githubusercontent.com/60264026/75685056-f29d3f80-5c67-11ea-8dcb-a1a5b989f5c9.png">

**Comment by cdaein** [comment]
A quick example I made worked fine: https://codepen.io/cdaein/pen/qBdjvxY?editors=1100

Check other parts of your code for any other errors. missing semicolons, parentheses, etc. It helps to open up a new template project and recreate a small section first.

Also, keep your viewbox of your SVG to have the same ratio as your grid column size. it looks like it's 4:3.

If you find a solution, add a comment here and close the issue.

**Comment by mattalancarter** [comment]
it looks like a problem with svg previewing or maybe with how brackets updates things. ive found that if the svg doesnt preview properly or if it breaks after i make a change, i simply need to close and restart the preview window. this isnt ideal but it works every time.
