### ISSUE TITLE
No hierarchy with text

### ISSUE THREAD

**Issue by elueck14** [cdaein/mica-gd220#8]
For some reason the text isn't following my <h1> <h2> or <p> tags. A have attached images of my code and the screen
<img width="648" alt="Screen Shot 2020-03-01 at 3 40 21 PM" src="https://user-images.githubusercontent.com/60264012/75795862-e6d17c00-5d40-11ea-8460-fb92fa2a4efd.png">
<img width="543" alt="Screen Shot 2020-03-01 at 3 40 40 PM" src="https://user-images.githubusercontent.com/60264012/75795863-e6d17c00-5d40-11ea-9889-f2fccdf26fd2.png">

**Comment by cdaein** [comment]
I see that all your text elements are not using the grid column/rows you have in the screenshot. Make sure every content is placed within one of the `row-X` and `col-X` divs.

If you get confused, do check back at the exercise we have done in class and compare it with your code.

**Comment by elueck14** [comment]
I tried on a new project template and placing the text in the box but it's still overlapping.
<img width="279" alt="Screen Shot 2020-03-04 at 12 36 45 AM" src="https://user-images.githubusercontent.com/60264012/75848692-e244ac00-5db0-11ea-91c6-338dbcff6a76.png">
![Uploading Screen Shot 2020-03-04 at 12.36.33 AM.png…]()

**Comment by cdaein** [comment]
Can you show your html and css?

**Comment by mattalancarter** [comment]
elizabeth—
all your text tags (h1, p, etc) will follow the hierarchy of their parent, which is the grid div, so they will all start at 0,0 of that div. if you want the type to follow hierarchy, try making a class with all the styles from h1 and using

 <p>
<span class="header">
HEADER STUFF HERE
</span>
<br>
Other stuff here
<br>
Other stuff here
</p>

or something like that. You can also just set:

.row-1.column-1 p {
top: 50px;
}

No matter what, all individual elements will start at 0,0. Hope this helps!
